name: Sphinx Build

on:
  push:
      branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello World"

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Sphinx docs
        run: sphinx-build -W -n -j auto -b html -d build/doctrees doc build/html


      - uses: actions/upload-artifact@v1
        with:
          name: TEMPLATE-docs
          path: build/html


