name: Hello World Workflow

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello World"


      - name: Build docs
        build-command: "sphinx-build -b html . _build"


      - uses: actions/upload-artifact@v1
        with:
          name: TEMPLATE-docs
          path: build/html
