name: Hello World

on:
  push:
    branches: [master]
  pull_request:
      branches: ['*']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello World"

      - name: Install
        shell: bash -l {0}
        run: python -m pip install --no-deps -e .

      - name: Build docs
        shell: bash -l {0}
        run: sphinx-build -W -n -j auto -b html -d build/doctrees doc build/html

      - uses: actions/upload-artifact@v1
        with:
          name: TEMPLATE-docs
          path: build/html

