name: Sphinx Build Actions

on:
  push:
      branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello World"

      - name: Setup conda environment
        uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: latest
          auto-update-conda: true
          python-version: 3.7
          environment-file: ci/requirements-docs.yml
          activate-environment: TEMPLATE-docs
          auto-activate-base: false

      - name: conda info
        shell: bash -l {0}
        run: conda info


      - name: conda list
        shell: bash -l {0}
        run: conda list


      - name: Install
        shell: bash -l {0}
        run: python -m pip install --no-deps -e .


      - name: Build Sphinx docs
        shell: bash -l {0}
        run: sphinx-build -W -n -j auto -b html -d build/doctrees doc build/html


      - uses: actions/upload-artifact@v1
        with:
          name: TEMPLATE-docs
          path: build/html


      - name: Trigger RTDs build
        uses: actions/checkout@v2
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}

