name: Sphinx Build Actions

on:
  push:
      branches: ['*']


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print Hello World
        run: echo "Hello World"

      - name: Setup conda environment
        uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: latest
          auto-update-conda: true
          python-version: 3.7
          environment-file: ci/requirements-docs.yml
          activate-environment: TEMPLATE-docs
          auto-activate-base: false

      - name: conda info
        shell: bash -l {0}
        run: conda info


      - name: conda list
        shell: bash -l {0}
        run: conda list


      - name: Install
        shell: bash -l {0}
        run: python -m pip install --no-deps -e .


      - name: Build Sphinx docs
        shell: bash -l {0}
        run: sphinx-build -W -n -j auto -b html -d build/doctrees doc build/html


      - uses: actions/upload-artifact@v1
        with:
          name: TEMPLATE-docs
          path: build/html


  # https://github.com/peaceiris/actions-gh-pages
      #- name: Deploy
       # if: success()
        #uses: peaceiris/actions-gh-pages@v3
        #with:
         # publish_branch: gh-pages
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          #publish_dir: build/html/



# Publish built docs to gh-pages branch.
    # ===============================
      - name: Commit documentation changes
        run: |
          git clone https://github.com/Nikitha-ramasetti/python_project_template.git --branch gh-pages --single-branch gh-pages
          cp -r docs/_build/html/* gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}

    # ===============================